services:   
 mongo:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_data_container:/data/db
    
 mysql:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_data_container:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 apt_scan_service:
  depends_on:
    - mongo
  image: r0790759/apt_scan_service
  ports:
    - 9001:9001
  links:
    - mongo
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo
   
 apt_car_service:
  depends_on:
    - mysql
  image: r0790759/apt_car_service
  ports:
    - 9000:9000
  links:
    - mysql
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql

apt_edge_service:
  depends_on:
    - apt_car_service
    - apt_scan_service
  image: miverboven/brank-edge-service-ex
  ports:
    - 9002:9002
  links:
    - apt_car_service
    - apt_scan_service
  environment:
   APT_SCAN_SERVICE_BASEURL: apt_scan_service:9001
   APT_CAR_SERVICE BASEURL: apt_car_service:9000
   
volumes:
 mongodb_data_container:
 mysql_data_container:
